/*employees 테이블에서 직원의 모든 정보, 부서이름, 도시 이름, 나라 이름, 대륙 이름 출력*/
SELECT *
FROM EMPLOYEES e ;

SELECT E.*, D.DEPARTMENT_NAME 부서, L.CITY 도시, C.COUNTRY_NAME 나라, R.REGION_NAME 대륙
FROM REGIONS r JOIN COUNTRIES c
					ON R.REGION_ID = C.REGION_ID 
				JOIN LOCATIONS l 
					ON C.COUNTRY_ID = L.COUNTRY_ID 
				JOIN DEPARTMENTS d 
					ON L.LOCATION_ID = D.LOCATION_ID 
				JOIN EMPLOYEES e 
					ON D.DEPARTMENT_ID = E.DEPARTMENT_ID  ;
					

/*DEPT 테이블의 LOC별 최대 월급을 받는 사원을 검색*/
SELECT *
FROM DEPT d ;

SELECT *
FROM EMP e ;

SELECT E.DEPTNO 지역, E.ENAME 사원이름, S.M 급여
FROM 
(
	SELECT MAX(SAL) M, DEPTNO 
	FROM EMP
	GROUP BY DEPTNO 
) S JOIN EMP e ON E.DEPTNO = S.DEPTNO
ORDER BY S.DEPTNO;


SELECT MAX(SAL), DEPTNO 
FROM EMP e 
GROUP BY DEPTNO  ;

/* TEAM테이블에서 울산현대와 삼성블루윙즈의 경기날짜 경기장이름 출력 */
SELECT TEAM_ID 
FROM TEAM t 
WHERE TEAM_NAME IN ('울산현대', '삼성블루윙즈');

SELECT *
FROM STADIUM s ;

SELECT *
FROM SCHEDULE s ;

SELECT *
FROM SCHEDULE s 
WHERE (HOMETEAM_ID = 'K01' AND AWAYTEAM_ID ='K02')
	OR (HOMETEAM_ID = 'K02' AND AWAYTEAM_ID ='K01');

SELECT *
FROM SCHEDULE s 
WHERE (HOMETEAM_ID = 'K01' OR AWAYTEAM_ID ='K01')
	AND (HOMETEAM_ID = 'K02' OR AWAYTEAM_ID ='K02');

/* TEAM테이블에서 울산현대와 삼성블루윙즈의 경기날짜 경기장이름 출력 */
SELECT S2.SCHE_DATE 경기날짜, S.STADIUM_NAME 경기장이름
FROM TEAM t JOIN STADIUM s 
		ON T.STADIUM_ID = S.STADIUM_ID
	JOIN SCHEDULE s2 
		ON S2.STADIUM_ID = S.STADIUM_ID 
	AND t.TEAM_NAME IN ('울산현대', '삼성블루윙즈')
WHERE S2.HOMETEAM_ID BETWEEN 
(SELECT TEAM_ID 
FROM TEAM t 
WHERE TEAM_NAME = '울산현대') AND 
(SELECT TEAM_ID 
FROM TEAM t 
WHERE TEAM_NAME = '삼성블루윙즈') 
AND 
S2.AWAYTEAM_ID BETWEEN 
(SELECT TEAM_ID 
FROM TEAM t 
WHERE TEAM_NAME = '울산현대') AND 
(SELECT TEAM_ID 
FROM TEAM t 
WHERE TEAM_NAME = '삼성블루윙즈')

/*PLAYER 테이블에서 팀별 최대 키를 가진 선수 조회*/
SELECT T.TEAM_ID 팀아이디, P.PLAYER_NAME, T.M 최대키 
FROM 
(
	SELECT TEAM_ID, MAX(HEIGHT) M
	FROM PLAYER p 
	GROUP BY TEAM_ID 
	ORDER BY TEAM_ID 
) T JOIN PLAYER p ON T.TEAM_ID = P.TEAM_ID AND T.M = P.HEIGHT 
ORDER BY T.TEAM_ID;

SELECT TEAM_ID, MAX(HEIGHT) M
FROM PLAYER p 
GROUP BY TEAM_ID 
ORDER BY TEAM_ID ;


/*득실차가 가장 많이 차이나는 경기의 경기장이름, 승리팀이름, 승리팀스코어, 패배팀이름, 패배팀스코어, 득실차를 조회*/
SELECT *
FROM STADIUM s;

SELECT *
FROM SCHEDULE s ;
SELECT *
FROM SCHEDULE s 
WHERE STADIUM_ID = 'B02';

SELECT MAX(HOME_SCORE)   
FROM SCHEDULE s ;
SELECT MAX(AWAY_SCORE)   
FROM SCHEDULE s ;

SELECT MIN(HOME_SCORE)
FROM SCHEDULE s ;
SELECT MIN(AWAY_SCORE)
FROM SCHEDULE s ;


SELECT MAX(ABS(HOME_SCORE - AWAY_SCORE)) 득실차 
FROM SCHEDULE s ;

SELECT STADIUM_ID , MAX(ABS(HOME_SCORE - AWAY_SCORE))
FROM SCHEDULE s 
GROUP BY STADIUM_ID  HAVING MAX(ABS(HOME_SCORE - AWAY_SCORE)) > (MAX(ABS(HOME_SCORE - AWAY_SCORE)) - 1);

SELECT STADIUM_ID , MAX(ABS(HOME_SCORE - AWAY_SCORE)) 
FROM SCHEDULE s 
GROUP BY STADIUM_ID  HAVING MAX(ABS(HOME_SCORE - AWAY_SCORE)) > 
(
	SELECT (MAX(ABS(HOME_SCORE - AWAY_SCORE)) - 1) 
	FROM SCHEDULE s
);

SELECT S.*
FROM 
(
	SELECT MAX(ABS(HOME_SCORE - AWAY_SCORE)) M, STADIUM_ID , SCHE_DATE
	FROM SCHEDULE MS
) MM JOIN SCHEDULE S ON MM.STADIUM_ID = S.STADIUM_ID AND MM.SCHE_DATE = S.SCHE_DATE;


SELECT STADIUM_ID , MAX(ABS(HOME_SCORE - AWAY_SCORE))
FROM SCHEDULE
GROUP BY STADIUM_ID ;

SELECT SCHE_DATE , MAX(ABS(HOME_SCORE - AWAY_SCORE))
FROM SCHEDULE
GROUP BY SCHE_DATE ;

/*득실차가 가장 많이 차이나는 경기의 경기장이름, 홈팀이름, 홈팀스코어, 어웨이팀이름, 어웨이팀스코어, 득실차를 조회*/
SELECT S2.STADIUM_NAME 경기장이름, T.TEAM_NAME 홈팀, S.HOME_SCORE 홈팀스코어, 
		(SELECT T2.TEAM_NAME FROM TEAM t2 WHERE T2.TEAM_ID=S.AWAYTEAM_ID) 어웨이팀, 
			S.AWAY_SCORE 어웨이팀스코어 ,ABS(S.HOME_SCORE - S.AWAY_SCORE) 득실차
FROM 
(
	SELECT STADIUM_ID , MAX(ABS(HOME_SCORE - AWAY_SCORE)) M
	FROM SCHEDULE
	GROUP BY STADIUM_ID
) SID JOIN SCHEDULE s 
	ON SID.STADIUM_ID = S.STADIUM_ID 
JOIN (
	SELECT SCHE_DATE , MAX(ABS(HOME_SCORE - AWAY_SCORE)) M
	FROM SCHEDULE
	GROUP BY SCHE_DATE) SDT
ON SDT.SCHE_DATE = S.SCHE_DATE 
JOIN STADIUM S2
ON S.STADIUM_ID = S2.STADIUM_ID 
JOIN TEAM t 
ON S2.STADIUM_ID = T.STADIUM_ID 
AND ABS(S.HOME_SCORE - S.AWAY_SCORE) = (
	SELECT MAX(ABS(HOME_SCORE - AWAY_SCORE))
	FROM SCHEDULE
);
