CREATE SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_BOARD;
/*===========================*/

CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE TBL_BOARD(
   BOARD_ID NUMBER CONSTRAINT PK_BOARD PRIMARY KEY,
   BOARD_TITLE VARCHAR2(500) NOT NULL,
   BOARD_CONTENT VARCHAR2(1000) NOT NULL,
   BOARD_REGISTER_DATE DATE,
   BOARD_UPDATE_DATE DATE,
   USER_ID NUMBER NOT NULL,
   CONSTRAINT FK_BOARD_USER FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
   ON DELETE CASCADE
);

SELECT * FROM TBL_BOARD;


/*===========================*/
CREATE TABLE TBL_BOARD(
	BOARD_ID NUMBER CONSTRAINT PK_BOARD PRIMARY KEY,
	BOARD_TITLE VARCHAR2(500) NOT NULL,
	BOARD_CONTENT VARCHAR2(1000) NOT NULL,
	BOARD_REGISTER_DATE DATE,
	BOARD_UPDATE_DATE DATE,
	USER_ID NUMBER NOT NULL,
	CONSTRAINT FK_BOARD_USER FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
	ON DELETE CASCADE
);
DROP TABLE TBL_BOARD ;

SELECT * FROM TBL_BOARD ;

SELECT * FROM TBL_BOARD WHERE BOARD_ID = ?;


/*게시글 추가*/
INSERT INTO TBL_BOARD 
(BOARD_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_REGISTER_DATE, BOARD_UPDATE_DATE, USER_ID)
VALUES (SEQ_BOARD.NEXTVAL, '네 번째 게시글', '테스트', SYSDATE, SYSDATE, 2);