/*================================*/
CREATE SEQUENCE SEQ_USER;

/*회원번호, 아이디, 이름, 비밀번호, 전화번호, 닉네임, 이메일, 주소, 생년월일, 성별, 추천인 아이디*/
CREATE TABLE TBL_USER(
   USER_ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
   USER_IDENTIFICATION VARCHAR2(500) UNIQUE NOT NULL,
   USER_NAME VARCHAR2(500) NOT NULL,
   USER_PASSWORD VARCHAR2(500) NOT NULL,
   USER_PHONE VARCHAR2(100) NOT NULL,
   USER_NICKNAME VARCHAR2(500),
   USER_EMAIL VARCHAR2(100) CONSTRAINT UK_USER UNIQUE NOT NULL,
   USER_ADDRESS VARCHAR2(500),
   USER_BIRTH DATE,
   USER_GENDER CHAR(1) DEFAULT 'N' CHECK(USER_GENDER IN('M', 'W', 'N')),
   USER_RECOMMENDER_ID VARCHAR2(500)
);

CREATE TABLE TBL_RECOMMEND(
   USER_ID NUMBER,
   RECOMMEND_COUNT NUMBER DEFAULT 0,
   CONSTRAINT FK_RECOMMEND_USER FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID),
   CONSTRAINT PK_RECOMMEND PRIMARY KEY(USER_ID)
);

CREATE OR REPLACE TRIGGER TRIGGER_RECOMMEND
AFTER
INSERT ON TBL_USER
FOR EACH ROW
DECLARE
BEGIN
   INSERT INTO TBL_RECOMMEND (USER_ID, RECOMMEND_COUNT) 
   VALUES(:NEW.USER_ID, 0);
END;

ALTER TABLE TBL_RECOMMEND DROP CONSTRAINT FK_RECOMMEND_USER;
ALTER TABLE TBL_RECOMMEND ADD 
CONSTRAINT FK_RECOMMEND_USER FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
ON DELETE CASCADE;

/*ALTER TABLE TBL_USER ADD RECOMMEND_COUNT NUMBER DEFAULT 0;*/
/*ALTER TABLE TBL_USER DROP COLUMN RECOMMEND_COUNT;*/

INSERT INTO TBL_USER
(USER_ID, USER_IDENTIFICATION, USER_NAME, USER_PASSWORD, USER_PHONE, USER_EMAIL, USER_ADDRESS)
VALUES(SEQ_USER.NEXTVAL, 'hds12345', '한동석', '1234', '01032341234', 'hds12345@gmail.com', '경기도 남양주시');

DELETE FROM TBL_USER WHERE USER_ID = 23;

SELECT * FROM TBL_USER;
SELECT * FROM TBL_RECOMMEND;

DROP TRIGGER TRIGGER_RECOMMEND;






/*================================*/


CREATE SEQUENCE SEQ_USER;
DROP SEQUENCE SEQ_USER;

/*회원번호, 아이디, 이름, 비밀번호, 전화번호, 닉네임, 이메일, 주소, 생년월일, 성별, 추천인 아이디*/
CREATE TABLE TBL_USER(
   USER_ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
   USER_IDENTIFICATION VARCHAR2(500) UNIQUE NOT NULL,
   USER_NAME VARCHAR2(500) NOT NULL,
   USER_PASSWORD VARCHAR2(500) NOT NULL,
   USER_PHONE VARCHAR2(100) NOT NULL,
   USER_NICKNAME VARCHAR2(500),
   USER_EMAIL VARCHAR2(100) CONSTRAINT UK_USER UNIQUE NOT NULL,
   USER_ADDRESS VARCHAR2(500),
   USER_BIRTH DATE,
   USER_GENDER CHAR(1) DEFAULT 'N' CHECK(USER_GENDER IN('M', 'W', 'N')),
   USER_RECOMMENDER_ID VARCHAR2(500)
);

CREATE TABLE TBL_RECOMMEND(
	USER_ID NUMBER,
	RECOMMEND_COUNT NUMBER DEFAULT 0,
	CONSTRAINT FK_RECOMMEND_USER FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID),
	CONSTRAINT PK_RECOMMEND PRIMARY KEY(USER_ID)
);

DROP TABLE TBL_RECOMMEND;

ALTER TABLE TBL_RECOMMEND DROP CONSTRAINT FK_RECOMMEND_USER;
ALTER TABLE TBL_RECOMMEND ADD
CONSTRAINT FK_RECOMMEND_USER FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
ON DELETE CASCADE; 

/*ALTER TABLE TBL_USER ADD RECOMMEND_COUNT NUMBER DEFAULT 0;*/
/*ALTER TABLE TBL_USER DROP COLUMN RECOMMEND_COUNT;*/

DELETE FROM TBL_USER;

CREATE TRIGGER TRIGGER_RECOMMEND
AFTER INSERT ON TBL_USER
BEGIN 
	INSERT INTO TBL_RECOMMEND
	VALUES(TBL_USER.USER_ID)
END;

CREATE OR REPLACE TRIGGER TRIGGER_RECOMMEND
AFTER
INSERT ON TBL_USER
FOR EACH ROW
DECLARE
BEGIN
   INSERT INTO TBL_RECOMMEND (USER_ID, RECOMMEND_COUNT) 
   VALUES(:NEW.USER_ID, 0);
END;



/*=======================================*/

INSERT INTO TBL_USER
(USER_ID, USER_IDENTIFICATION, USER_NAME, USER_PASSWORD, USER_PHONE, USER_EMAIL, USER_ADDRESS)
VALUES(SEQ_USER.NEXTVAL, 'hds1234', '한동석', '1234', '01012341234', 'hds1234@gmail.com', '경기도 남양주시');

INSERT INTO TBL_USER
(USER_ID, USER_IDENTIFICATION, USER_NAME, USER_PASSWORD, USER_PHONE, USER_EMAIL, USER_ADDRESS, USER_RECOMMENDER_ID)
VALUES(SEQ_USER.NEXTVAL, 'ymw1234', '윤민우', '1234', '01056785678', 'ymw1234@gmail.com', '서울시 강남구', 'hds1234');
INSERT INTO TBL_USER
(USER_ID, USER_IDENTIFICATION, USER_NAME, USER_PASSWORD, USER_PHONE, USER_EMAIL, USER_ADDRESS, USER_RECOMMENDER_ID)
VALUES(SEQ_USER.NEXTVAL, 'ksy1234', '김세윤', '1234', '01012345678', 'ksy1234@gmail.com', '경기도 성남시', 'hds1234');

SELECT * FROM TBL_USER;

SELECT COUNT(USER_RECOMMENDER_ID) 
FROM TBL_USER tu 
WHERE USER_RECOMMENDER_ID = 'hds1234';

/*나를 추천한 사람*/
SELECT USER_NAME 
FROM TBL_USER tu 
WHERE USER_RECOMMENDER_ID = 'hds1234' ;

/*내가 추천한 사람*/
SELECT * FROM TBL_USER t WHERE USER_IDENTIFICATION =  (SELECT USER_RECOMMENDER_ID FROM TBL_USER	WHERE USER_IDENTIFICATION = 'ymw1234');

/*회원정보 수정*/
UPDATE TBL_USER
SET USER_NAME=?, USER_PASSWORD=?, USER_PHONE=?, USER_NICKNAME=?, USER_EMAIL = ?, USER_ADDRESS=?, USER_BIRTH=?, USER_GENDER=?, USER_RECOMMENDER_ID=?
WHERE USER_ID=?;

/*"SET USER_NAME = ?, USER_PASSWORD = ?, USER_PHONE_NUMBER = ?, USER_NICKNAME = ?, USER_EMAIL = ?, USER_ADDRESS = ?*/

/*내가 추천한 // 사람*/

SELECT *
FROM TBL_USER tu 
WHERE USER_RECOMMENDER_ID = 'hds1234';

SELECT *  FROM TBL_USER tu WHERE USER_IDENTIFICATION = 'hds1234';

SELECT *
FROM TBL_USER tu 
WHERE USER_RECOMMENDER_ID = 'korea1234';

/*욱성님 아이디->  내가 추천한 사람*/

SELECT * 
FROM TBL_USER tu 
WHERE USER_IDENTIFICATION = 
(
	SELECT USER_RECOMMENDER_ID 
	FROM TBL_USER tu 
	WHERE USER_IDENTIFICATION = 'korea7403';
);

/*01012341234*/
SELECT USER_IDENTIFICATION FROM TBL_USER tu WHERE USER_PHONE = '01012341234';


/*비밀번호 변경*/
/*아이디, 바꿀 비밀번호*/

UPDATE TBL_USER SET USER_PASSWORD = '1234' WHERE USER_IDENTIFICATION = 'korea1234';

/*회원정보 변경*/
UPDATE TBL_USER 
SET 
WHERE USER_ID = '1';

UPDATE TBL_USER SET USER_IDENTIFICATION='', USER_NAME='', USER_PASSWORD='', USER_PHONE='', USER_NICKNAME='', USER_ADDRESS='', USER_GENDER='N' WHERE USER_ID ='1';










